name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - run: npm run build
        env:
          TURBO_TOKEN: zTHFvBXbKl8o5xAsw34mQSBD
          TURBO_TEAM: alanandrade

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: touch storybook-static/.nojekyll && npm run deploy -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
